version: 2.1
jobs:
  build:
    docker:
      - image: theasp/clojurescript-nodejs:latest

    working_directory: ~/repo

    steps:
      - checkout
      # TODO: Cache the downloaded dependencies
      - run:
          name: Install Clojure CLI
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
            chmod +x linux-install-1.10.1.536.sh
            ./linux-install-1.10.1.536.sh

      - run:
          name: Install root dependencies
          command: npm install

      - run:
          name: Check if common dependencies are in sync
          command: npm run check_common_dependencies

      - run:
          name: Subpackage lint and tests
          command: |
            npm run for_each_package -- 'npm install && npm run lint && npm test'

      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Release
                command: npx semantic-release
