version: 2
jobs:
  build:
    docker:
      - image: theasp/clojurescript-nodejs:latest

    working_directory: ~/repo

    steps:
      - checkout
      
      # TODO: Cache the downloaded dependencies
      - run:
          name: Install Clojure CLI
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
            chmod +x linux-install-1.10.1.536.sh
            ./linux-install-1.10.1.536.sh

      - run: npm install
      - run: npm run check_common_dependencies

      - run: npx lerna bootstrap

      - run:
          name: Lint
          command: |
            npm run remove_build_caches
            for package in $(npm run --silent get_packages)
            do
              cd $package
              npm run lint
              cd ../..
            done

      - run:
          name: Tests
          command: |
            npm run remove_build_caches
            for package in $(npm run --silent get_packages)
            do
              cd $package
              npm run compile-tests
              npm run run-tests
              cd ../..
            done
