version: 2
jobs:
  build:
    docker:
      - image: theasp/clojurescript-nodejs:latest

    working_directory: ~/repo

    steps:
      - checkout
      
      # TODO: Cache the downloaded dependencies
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run check_common_dependencies
      - run: npm run lint
      - run: npm test
