version: 2
jobs:
  build:
    docker:
      - image: theasp/clojurescript-nodejs:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - clj-dependencies-{{ checksum "shadow-cljs.edn" }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - clj-dependencies-

      - run: make deps

      - save_cache:
          paths:
            - ~/.m2
            - ~/repo/node_modules
          key: clj-dependencies-{{ checksum "shadow-cljs.edn" }}-{{ checksum "package.json" }}

      # run tests!
      - run: make test
