version: 2
jobs:
  build:
    docker:
      - image: theasp/clojurescript-nodejs:latest

    working_directory: ~/repo

    steps:
      - checkout
      # TODO: Cache the downloaded dependencies
      - run:
          name: Install Clojure CLI
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
            chmod +x linux-install-1.10.1.536.sh
            ./linux-install-1.10.1.536.sh

      - run:
          name: Install root dependencies
          command: npm install

      - run:
          name: Check if common dependencies are in sync
          command: npm run check_common_dependencies

      - run:
          name: Install subpackage dependencies
          command: npx lerna bootstrap

      - run:
          name: Lint
          command: |
            npm run clean
            for package in $(npm run --silent get_packages)
            do
              cd $package
              npm run lint
              cd ../..
            done

      - run:
          name: Tests
          command: |
            npm run clean
            for package in $(npm run --silent get_packages)
            do
              cd $package
              npm run compile-tests
              npm run run-tests
              cd ../..
            done

      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run: echo "I am on the master branch"
      - when:
          condition:
            not:
              equal: [master, << pipeline.git.branch >>]
          steps:
            - run: echo "I am not on the master branch"
